<?php

namespace Test\Hurah\Types\Type;

use Hurah\Types\Type\Language;
use PHPUnit\Framework\TestCase;

class LanguageTest extends TestCase
{

    private Language $oLanguage;
    public function setUp(): void
    {
        $this->oLanguage = new Language('Dutch');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testToIso3()
    {
        $this->assertEquals('nld', $this->oLanguage->toIso3());
    }

    public function testToIso2()
    {
        $this->assertEquals('nl', $this->oLanguage->toIso2());
    }

    public function test__toString()
    {
        $this->assertEquals('Dutch', "{$this->oLanguage}");
    }

    public function testFromIso()
    {
        $oLanguage2 = Language::fromIso('nl');
        $this->assertEquals('Dutch', "{$oLanguage2}");

        $oLanguage3 = Language::fromIso('nld');
        $this->assertEquals('Dutch', "{$oLanguage3}");
    }

}
