<?php

namespace Test\Hurah\Types\Type;

use Hurah\Types\Type\Tag;
use Hurah\Types\Type\TagCollection;
use PHPUnit\Framework\TestCase;

class TagCollectionTest extends TestCase
{

    private TagCollection $oTagCollection;

    public function setUp(): void
    {
        $this->oTagCollection = new TagCollection();
        $this->oTagCollection->add(new Tag("test"));
        $this->oTagCollection->add(new Tag("#test2"));


        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testHas()
    {

        $this->assertTrue($this->oTagCollection->has(new Tag('#test2')));
        $this->assertTrue($this->oTagCollection->has(new Tag('test2')));
        $this->assertFalse($this->oTagCollection->has(new Tag('test3')));

    }

    public function testMerge()
    {
        $oNewCollection = new TagCollection();
        $oNewCollection->add(new Tag('test3'));
        $oNewCollection->add(new Tag('#test4'));
        $oCombinedCollection = $this->oTagCollection->merge($oNewCollection);
        $this->assertTrue($oCombinedCollection->has(new Tag('test2')));
        $this->assertTrue($oCombinedCollection->has(new Tag('#test4')));

    }
}
