<?php

namespace Hurah\Types\Type;

use Exception;
use Hurah\Types\Exception\InvalidArgumentException;
use Hurah\Types\Util\JsonUtils;
use function is_string;
use function preg_replace;
use function strpos;


/**
 * Represents a tag of some sort
 * Class Tag
 * @package Hurah\Type
 */
class Tag extends PlainText implements IGenericDataType, ITestable
{

    public function __construct($sValue = null)
    {
        if(is_string($sValue))
        {
            $sValue = preg_replace('/^#/', '', $sValue);
        }
        parent::__construct($sValue);
    }

    /**
     * Returns true when $sSubject contains this tag.
     * @param string $sSubject
     *
     * @return bool
     */
    public function test($sSubject): bool
    {
        if(strpos($sSubject, "$this"))
        {
            return true;
        }
        return false;
    }


    public function __toString():string
    {
        return '#' . parent::__toString(); // TODO: Change the autogenerated stub
    }
}
